### PR TITLE
Update to LPub3D v2.4.5 release

### PR DESCRIPTION
**Pull request by trevorsandy**

### CODE REVIEW

**Comment by hfiguiere** [comment]
```
error: /srv/buildbot/worker/build-x86_64-6/build/builddir/export/share/icons/hicolor/scalable/mimetypes/io.github.trevorsandy.LPub3D.x-ldraw.svg is not a valid icon: Expected a square icon but got: 640x480
```

**Comment by trevorsandy** [comment]
It has been 23 hours since a successful build completed and nothing is published.

After some research, I understand that publishing is automatically triggered when this pull request is merged into the flathub:master branch; however, I do not have the privilege to merge PRs into flathub:master. Please advise?

Cheers,

**Comment by hfiguiere** [comment]
No it doesn't publish automatically. PR have to be merged.

@barthalion can you check why @trevorsandy doesn't have permissions to merge?

In the mean time I'll merge.

**Comment by trevorsandy** [comment]
Many thanks.

Note that I also cannot publish from Buildbor: Flathub. The following message is returned:

Cannot publish: You need commit permissions to https://github.com/flathub/io.github.trevorsandy.LPub3D.git or flathub admin status

Cheers,

**Comment by hfiguiere** [comment]
The `master` branch is protected so there is no direct push.

**Comment by trevorsandy** [comment]
Very well. So what is the recommended process to publish an update on your platform?

Cheers,

**Comment by hfiguiere** [comment]
Like you did: a pull request. (you should have had merge permissions, but I can't check that myself, I don't have proper privileges)

Note: I had that update on my todo list when I saw the PR.

**Comment by trevorsandy** [comment]
I would like to re-release v2.4.5 to incorporate a final update. This means the major, minor, patch values of the appdata file will not change but the date and revision in the releases tag will.

My aim is to retag my master branch and generate a new pull request.

My question is will the Flathub Buildbot allow this scenario to complete the publish process? Many thanks.

Cheers,

**Comment by hfiguiere** [comment]
From general point of view, retagging a published tag is a BAD practice.

Flathub will no car as long as the revision tag will match.

**Comment by barthalion** [comment]
Hi @trevorsandy, I've just sent you an invite.

**Comment by trevorsandy** [comment]
Hello @barthalion, I’ve accepted the invitation. Many thanks.

Cheers,

**Pull request merged**
